SiteAmanda/config/routes.rb
Rails.application.routes.draw do
  resources :topicos do
    resources :comentarios
  end
  resources :formularios, :topicos
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'formularios/aceitos'
  #get 'formularios/recusados'
end

SiteAmanda/app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :topico
  validates :usuario, presence: true
  validates :texto, presence: true
  validates_length_of :texto, minimum: 3, maximum: 1000
end

SiteAmanda/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @topico = Topico.find(params[:topico_id])
    @comentario = @topico.comentarios.create(comentario_params)

    redirect_to topico_path(@topico)
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    #respond_to do |format|
    #  if @comentario.update(comentario_params)
    #    format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
    #    format.json { render :show, status: :ok, location: @comentario }
    #  else
    #    format.html { render :edit }
    #    format.json { render json: @comentario.errors, status: :unprocessable_entity }
    #  end
    #end
    manipulacaoControle(@comentario, @comentario.update(comentario_params), 'Comentario', 'updated.', :ok, :edit)
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to topicos_path, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:usuario, :texto, :topico_id)
    end
end

SiteAmanda/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

SiteAmanda/app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto, id: :comentario_texto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

SiteAmanda/app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

SiteAmanda/app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Texto</th>
      <th>Topico</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.usuario %></td>
        <td><%= comentario.texto %></td>
        <td><%= comentario.topico %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

SiteAmanda/app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

SiteAmanda/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @comentario.texto %>
</p>

<p>
  <strong>Topico:</strong>
  <%= @comentario.topico %>
</p>
<%= link_to 'Destroy', comentario, method: :destroy, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>