SiteAmanda/config/routes.rb
Rails.application.routes.draw do
  resources :topicos do
    resources :comentarios
  end
  resources :formularios, :topicos
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'formularios/aceitos'
  #get 'formularios/recusados'
end

SiteAmanda/app/models/topico.rb
class Topico < ApplicationRecord
  has_many :comentarios, dependent: :destroy
	validates :titulo, presence: true
	validates_length_of :titulo, minimum: 5, maximum: 50
	validates :corpo, presence: true
	validates_length_of :corpo, minimum: 10, maximum: 180
end

SiteAmanda/app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]

  # GET /topicos
  # GET /topicos.json
  def index
    @topicos = Topico.all
  end

  # GET /topicos/1
  # GET /topicos/1.json
  def show
  end

  # GET /topicos/new
  def new
    @topico = Topico.new
  end

  # GET /topicos/1/edit
  def edit
  end

  # POST /topicos
  # POST /topicos.json
  def create
    @topico = Topico.new(topico_params)
    #respond_to do |format|
    #  if @topico.save
    #    format.html { redirect_to @topico, notice: 'Topico was successfully created.' }
    #    format.json { render :show, status: :created, location: @topico }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @topico.errors, status: :unprocessable_entity }
    #  end
    #end
    manipulacaoControle(@topico, @topico.save, 'Topico', 'created.', :created, :new)
  end

  # PATCH/PUT /topicos/1
  # PATCH/PUT /topicos/1.json
  def update
   # respond_to do |format|
   #   if @topico.update(topico_params)
   #     format.html { redirect_to @topico, notice: 'Topico was successfully updated.' }
   #     format.json { render :show, status: :ok, location: @topico }
   #   else
   #     format.html { render :edit }
   #     format.json { render json: @topico.errors, status: :unprocessable_entity }
   #   end
   # end
    manipulacaoControle(@topico, @topico.update(topico_params), 'Topico', 'updated.', :ok, :edit)
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.json
  def destroy
    @topico.destroy
    respond_to do |format|
      format.html { redirect_to topicos_url, notice: 'Topico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topico
      @topico = Topico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topico_params
      params.require(:topico).permit(:titulo, :corpo)
    end
end

SiteAmanda/app/helpers/topicos_helper.rb
module TopicosHelper
end

SiteAmanda/app/views/topicos/_form.html.erb
<%= form_with(model: topico, local: true) do |form| %>
  <% if topico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

      <ul>
      <% topico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :topico_titulo %>
  </div>

  <div class="field">
    <%= form.label :corpo %>
    <%= form.text_area :corpo, id: :topico_corpo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

SiteAmanda/app/views/topicos/edit.html.erb
<h1>Editing Topico</h1>

<%= render 'form', topico: @topico %>

<%= link_to 'Show', @topico %> |
<%= link_to 'Back', topicos_path %>

SiteAmanda/app/views/topicos/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.admin == true%>
  <%= link_to 'New Topico', new_topico_path %>
<% end %>
<%= link_to 'Voltar', root_path %>
<h1>Topicos</h1>
<h5>Logado como: <%= current_user.email %></h5>
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Corpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topicos.each do |topico| %>
      <tr>
        <td><%= topico.titulo %></td>
        <td><%= topico.corpo %></td>
        <td><%= link_to 'Show', topico %></td>
        <% if current_user.admin == true%>
        	<td><%= link_to 'Edit', edit_topico_path(topico) %></td>
        	<td><%= link_to 'Destroy', topico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

SiteAmanda/app/views/topicos/new.html.erb
<h1>New Topico</h1>

<%= render 'form', topico: @topico %>

<%= link_to 'Back', topicos_path %>

SiteAmanda/app/views/topicos/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.admin == true%>
	<%= link_to 'Edit', edit_topico_path(@topico) %> |
<% end %>
<%= link_to 'Back', topicos_path %>
<p>
  <strong>Titulo:</strong>
  <%= @topico.titulo %>
</p>

<p>
  <strong>Corpo:</strong>
  <%= @topico.corpo %>
</p>

<h2>Comentarios</h2>
<% @topico.comentarios.each do |comentario|%>
	<p>
		<strong>Autor:</strong>
		<%= comentario.usuario %>
	</p>

	<p>
		<strong>Texto:</strong>
		<%= comentario.texto %>
	</p>
	<%if comentario.usuario == current_user.email or current_user.admin %>
	<%= link_to 'Destroy', topico_comentario_path(@topico, comentario), method: :delete, data: { confirm: 'Are you sure?' }%>
			<% end  %>
<% end %>

<%= form_for([@topico, @topico.comentarios.build]) do |c|%>

	<div class="field">
		<%= c.label :usuario %>
		<%= c.text_field :usuario, id: :comentario_usuario, :value => current_user.email, :readonly => true %>
	</div>

	<div class="field">
		<%= c.label :texto %>
		<%= c.text_area :texto, id: :comentario_texto %>
	</div>

	<div class="actions">
		<%= c.submit %>
	</div>
<% end %>