SiteAmanda/config/routes.rb
Rails.application.routes.draw do
  resources :topicos do
    resources :comentarios
  end
  resources :formularios, :topicos
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'formularios/aceitos'
  #get 'formularios/recusados'
end

SiteAmanda/app/models/formulario.rb
class Formulario < ApplicationRecord
  validates :contratante, presence: true
  validates_length_of :contratante, maximum: 100
  validates :descricao, presence: true
  validates_length_of :descricao, minimum: 10, maximum: 1000
  validates :local, presence: true
  validates_length_of :local, minimum: 5, maximum: 100
  validates :data, presence: true
  validates_inclusion_of :status, :in => ["Aceito", "Recusado", "Pendente"]


end

SiteAmanda/app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  before_action :set_formulario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /formularios
  # GET /formularios.json
  def index
    @formularios = Formulario.all
    $statusA = "Pendente"
  end

  # GET /formularios/1
  # GET /formularios/1.json
  def show
  end

  # GET /formularios/new
  def new
    @formulario = Formulario.new
  end

  # GET /formularios/1/edit
  def edit
  end

  # POST /formularios
  # POST /formularios.json
  def create
    @formulario = Formulario.new(formulario_params)
    @formulario.email = current_user.email
    @formulario.status = "Pendente"
    #respond_to do |format|
    #  if @formulario.save
    #    format.html { redirect_to @formulario, notice: 'Formulario was successfully created.' }
    #    format.json { render :show, status: :created, location: @formulario }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @formulario.errors, status: :unprocessable_entity }
    #  end
    #end
    manipulacaoControle(@formulario, @formulario.save, 'Formulario', 'created.', :created, :new)
  end

  # PATCH/PUT /formularios/1
  # PATCH/PUT /formularios/1.json
  def update
    #respond_to do |format|
    #  if @formulario.update(formulario_params)
    #    format.html { redirect_to @formulario, notice: 'Formulario was successfully updated.' }
    #    format.json { render :show, status: :ok, location: @formulario }
    #  else
    #    format.html { render :edit }
    #    format.json { render json: @formulario.errors, status: :unprocessable_entity }
    #  end
    #end
    manipulacaoControle(@formulario, @formulario.update(formulario_params), 'Formulario', 'updated.', :ok, :edit)
  end

  # DELETE /formularios/1
  # DELETE /formularios/1.json
  def destroy
    @formulario.destroy
    respond_to do |format|
      format.html { redirect_to formularios_url, notice: 'Formulario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #GET /formularios/aceitos
  def aceitos
    @formularios = Formulario.all
    $statusA = "Aceito"
  end

  #GET /formularios/recusados
  def recusados
    @formularios = Formulario.all
    $statusA = "Recusado"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulario
      @formulario = Formulario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formulario_params
      params.require(:formulario).permit(:email, :contratante, :descricao, :data, :local, :status)
    end
end

SiteAmanda/app/helpers/formularios_helper.rb
module FormulariosHelper
end

SiteAmanda/app/views/formularios/_form.html.erb
<%= form_with(model: formulario, local: true) do |form| %>
  <% if formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
      <% formulario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contratante %>
    <%= form.text_field :contratante, id: :formulario_contratante %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :formulario_descricao %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_field :data, id: :formulario_data %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local, id: :formulario_local %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

SiteAmanda/app/views/formularios/aceitos.html.erb
<h1>Formularios</h1>
<%= link_to 'Home', root_path%>
<% if current_user %>
  <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% end %>
<h5>Logado como: <%= current_user.email %></h5>
<%= link_to 'Voltar', formularios_path %>

<table>
  <thead>
  <tr>
    <th><strong>Contratante</strong></th>
    <th><strong>Data</strong></th>
    <th><strong>Local</strong></th>
    <th><strong>Status</strong></th>
  </tr>
  </thead>

  <tbody>
  <% @formularios.each do |formulario| %>
    <% if current_user.email == formulario.email and formulario.status == "Aceito"%>
      <tr>
        <!--<td><%= formulario.email %></td>-->
        <td><%= formulario.contratante %></td>
        <!--<td><%= formulario.descricao %></td>-->
        <td><%= formulario.data %></td>
        <td><%= formulario.local %></td>
        <td><%= formulario.status %></td>
        <td><%= link_to 'Show', formulario %></td>
        <td><%= link_to 'Edit', edit_formulario_path(formulario) %></td>
        <td><%= link_to 'Destroy', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

SiteAmanda/app/views/formularios/edit.html.erb
<h1>Editing Formulario</h1>

<%= form_with(model: @formulario, local: true) do |form| %>
  <% if @formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
        <% @formulario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :formulario_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @formulario %> |
<%= link_to 'Back', formularios_path %>

SiteAmanda/app/views/formularios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formularios</h1>
<%= link_to 'Home', root_path%>
<% if current_user %>
  <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% end %>
<h5>Logado como: <%= current_user.email %></h5>
<% if current_user.admin == false%>
<%= link_to 'Novo Formulario', new_formulario_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th><strong>Contratante</strong></th>
      <th><strong>Data</strong></th>
      <th><strong>Local</strong></th>
      <th><strong>Status</strong></th>
    </tr>
  </thead>
  <% if current_user.admin == false%>
  <tbody>
    <% @formularios.each do |formulario| %>
      <% if current_user.email == formulario.email%>
      <tr>
        <!--<td><%= formulario.email %></td>-->
        <td><%= formulario.contratante %></td>
        <!--<td><%= formulario.descricao %></td>-->
        <td><%= formulario.data %></td>
        <td><%= formulario.local %></td>
        <td><%= formulario.status %></td>
        <td><%= link_to 'Ver', formulario %></td>
        <td><%= link_to 'Destroy', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
  <% else%>
    <tbody>
    <% @formularios.each do |formulario| %>
        <tr>
          <!--<td><%= formulario.email %></td>-->
          <td><%= formulario.contratante %></td>
          <!--<td><%= formulario.descricao %></td>-->
          <td><%= formulario.data %></td>
          <td><%= formulario.local %></td>
          <td><%= formulario.status %></td>
          <td><%= link_to 'Ver', formulario %></td>
          <td><%= link_to 'Responder', edit_formulario_path(formulario) %></td>
          <td><%= link_to 'Destroy', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  <% end %>


</table>

<br>

SiteAmanda/app/views/formularios/new.html.erb
<h1>New Formulario</h1>
<% if current_user.admin == false%>
<%= render 'form', formulario: @formulario %>

<%= link_to 'Ver Meus Formularios', formularios_path %>
<% else%>
  <%= link_to 'Ver Formularios Enviados', formularios_path %>
<% end %>

SiteAmanda/app/views/formularios/recusados.html.erb
<h1>Formularios</h1>
<%= link_to 'Home', root_path%>
<% if current_user %>
  <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% end %>
<h5>Logado como: <%= current_user.email %></h5>
<%= link_to 'Voltar', formularios_path %>

<table>
  <thead>
  <tr>
    <th><strong>Contratante</strong></th>
    <th><strong>Data</strong></th>
    <th><strong>Local</strong></th>
    <th><strong>Status</strong></th>
  </tr>
  </thead>

  <tbody>
  <% @formularios.each do |formulario| %>
    <% if current_user.email == formulario.email and formulario.status == "Recusado"%>
      <tr>
        <!--<td><%= formulario.email %></td>-->
        <td><%= formulario.contratante %></td>
        <!--<td><%= formulario.descricao %></td>-->
        <td><%= formulario.data %></td>
        <td><%= formulario.local %></td>
        <td><%= formulario.status %></td>
        <td><%= link_to 'Show', formulario %></td>
        <td><%= link_to 'Edit', edit_formulario_path(formulario) %></td>
        <td><%= link_to 'Destroy', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

SiteAmanda/app/views/formularios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @formulario.email %>
</p>

<p>
  <strong>Contratante:</strong>
  <%= @formulario.contratante %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @formulario.descricao %>
</p>

<p>
  <strong>Data:</strong>
  <%= @formulario.data %>
</p>

<p>
  <strong>Local:</strong>
  <%= @formulario.local %>
</p>

<p>
  <strong>Status:</strong>
  <%= @formulario.status %>
</p>
<% if current_user.admin == true%>
<%= link_to 'Edit', edit_formulario_path(@formulario) %> |
<% end%>
<%= link_to 'Back', formularios_path %>